"""
promptcanary.cli
~~~~~~~~~~~~~~~~

PromptCanary CLI — built with Typer + Rich.

Commands:
  init     Scaffold a new canary suite directory.
  run      Run a canary suite against a provider.
  compare  Compare a saved baseline to a new run.
  report   Generate a report from saved JSON results.
  baselines List or inspect saved baselines.
"""

from __future__ import annotations

import json
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

app = typer.Typer(
    name="promptcanary",
    help=(
        "🐦 PromptCanary — Detect silent behavioral drift in LLM providers.\n\n"
        "Catch when your provider silently changes — before it breaks production."
    ),
    add_completion=False,
    rich_markup_mode="rich",
    no_args_is_help=True,
)

console = Console()
err_console = Console(stderr=True)


# ─────────────────────────────────────────────────────────────────────────────
# init
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def init(
    name: str = typer.Argument(
        "my-canary-suite",
        help="Name of the directory and suite to create.",
    ),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing suite."),
) -> None:
    """Scaffold a new canary suite with example prompts and probes.

    Creates a ``canary.yaml``, a ``baselines/`` directory, and example files.
    """
    suite_dir = Path(name)
    if suite_dir.exists() and not force:
        err_console.print(
            f"[red]Directory '{name}' already exists.[/red] Use [cyan]--force[/cyan] to overwrite."
        )
        raise typer.Exit(1)

    suite_dir.mkdir(parents=True, exist_ok=True)
    (suite_dir / "baselines").mkdir(exist_ok=True)

    # Write example canary.yaml
    yaml_content = f"""\
# PromptCanary Suite — {name}
# Generated by `promptcanary init`
# Run: promptcanary run --config {name}/canary.yaml --provider openai/gpt-5.4

name: {name}
description: "Canary suite for detecting silent behavioral drift."
tags:
  - production
  - my-team

# ── Probes ────────────────────────────────────────────────────────────────────
# Each probe type checks a different aspect of model behavior.
# Mix and match to cover the dimensions that matter to your use case.
probes:
  - type: json_validity           # Does the model return valid JSON when asked?
  - type: keyword_presence        # Are expected keywords present?
    required_keywords: ["Paris"]
    forbidden_keywords: []
  - type: response_length         # Has verbosity drifted?
    min_chars: 10
    max_chars: 2000
  - type: refusal                 # Is the model refusing when it shouldn't?
    expect_refusal: false
  - type: direct_answer           # No "Great question!" preamble?
    expect_direct: true

# ── Prompts ────────────────────────────────────────────────────────────────────
# Add prompts that represent real patterns in your production system.
prompts:
  - text: "What is the capital of France? Reply in one sentence."
    description: "Basic geography — should be simple and direct."
    expected_keywords: ["Paris"]
    tags: [geography, simple]

  - text: "Return a JSON object with keys: name (string) and age (integer). Example values only."
    description: "JSON formatting canary — tests consistent output structure."
    tags: [json, format]

  - text: |
      Explain what photosynthesis is in 2-3 sentences.
      Keep it concise and use plain language.
    description: "Verbosity and clarity canary."
    tags: [explanation, verbosity]
"""
    (suite_dir / "canary.yaml").write_text(yaml_content, encoding="utf-8")

    # Write .env.example
    env_example = """\
# PromptCanary environment variables
# Copy to .env and fill in your API keys.

# OpenAI
OPENAI_API_KEY=sk-...

# Anthropic
ANTHROPIC_API_KEY=sk-ant-...

# Google
GEMINI_API_KEY=...
"""
    (suite_dir / ".env.example").write_text(env_example, encoding="utf-8")

    # Write README stub
    readme = f"""\
# {name} — PromptCanary Suite

This canary suite detects silent behavioral drift in your LLM provider.

## Quick Start

```bash
# Install dependencies
pip install promptcanary

# Set your API key
export OPENAI_API_KEY=sk-...

# Run and save baseline
promptcanary run --config canary.yaml --provider openai/gpt-5.4 --save-baseline

# Run again later to detect drift
promptcanary run --config canary.yaml --provider openai/gpt-5.4

# Compare against baseline
promptcanary compare --baseline baselines/latest.json --current results.json
```

## Adding to CI

See [PromptCanary docs](https://github.com/promptcanary/promptcanary) for GitHub Action setup.
"""
    (suite_dir / "README.md").write_text(readme, encoding="utf-8")

    console.print()
    console.print(
        Panel(
            f"[green bold]✅ Created canary suite: [cyan]{name}/[/cyan][/green bold]\n\n"
            f"  [dim]📄[/dim] [cyan]{name}/canary.yaml[/cyan]  — Edit your prompts and probes\n"
            f"  [dim]📁[/dim] [cyan]{name}/baselines/[/cyan]  — Baselines saved here\n"
            f"  [dim]📝[/dim] [cyan]{name}/.env.example[/cyan] — Copy to .env and add API keys\n\n"
            "[bold]Next steps:[/bold]\n"
            f"  1. [cyan]cd {name}[/cyan] and edit [cyan]canary.yaml[/cyan]\n"
            f"  2. Set your API key: [cyan]export OPENAI_API_KEY=sk-...[/cyan]\n"
            f"  3. Run: [cyan]promptcanary run --config canary.yaml --provider openai/gpt-5.4 --save-baseline[/cyan]",
            title="[bold blue]PromptCanary Init[/bold blue]",
            border_style="green",
        )
    )


# ─────────────────────────────────────────────────────────────────────────────
# run
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def run(
    config: Path = typer.Option(
        Path("canary.yaml"),
        "--config",
        "-c",
        help="Path to canary.yaml config file.",
        exists=False,  # We check manually for a better error message
    ),
    provider: str = typer.Option(
        ...,
        "--provider",
        "-p",
        help='LiteLLM model string, e.g. "openai/gpt-5.4" or "anthropic/claude-sonnet-4-6".',
    ),
    temperature: float = typer.Option(0.0, "--temperature", "-t", help="Sampling temperature."),
    max_tokens: int = typer.Option(1024, "--max-tokens", help="Max tokens in response."),
    seed: int | None = typer.Option(42, "--seed", help="Random seed for reproducibility."),
    save_baseline: bool = typer.Option(
        False,
        "--save-baseline",
        "-s",
        help="Save the run result as a new baseline.",
    ),
    baseline_dir: Path = typer.Option(
        Path("baselines"),
        "--baseline-dir",
        help="Directory for baseline storage.",
    ),
    output_json: Path | None = typer.Option(
        None,
        "--output-json",
        "-o",
        help="Save raw JSON results to this path.",
    ),
    output_md: Path | None = typer.Option(
        None,
        "--output-md",
        help="Save a Markdown report to this path.",
    ),
    output_html: Path | None = typer.Option(
        None,
        "--output-html",
        help="Save an HTML report to this path.",
    ),
    fail_on_failure: bool = typer.Option(
        False,
        "--fail-on-failure",
        help="Exit with code 1 if any probe fails (useful for CI).",
    ),
    no_progress: bool = typer.Option(False, "--no-progress", help="Disable progress display."),
) -> None:
    """Run a canary suite against an LLM provider.

    Loads the suite from [cyan]canary.yaml[/cyan], queries the provider,
    applies all probes, and prints a rich report.

    [bold]Examples:[/bold]

    [dim]# Basic run[/dim]
    promptcanary run --provider openai/gpt-5.4

    [dim]# Run and save baseline[/dim]
    promptcanary run --provider anthropic/claude-sonnet-4-6 --save-baseline

    [dim]# Custom config with output files[/dim]
    promptcanary run -c my-suite/canary.yaml -p openai/gpt-5.4 -o results.json --output-html report.html
    """
    from promptcanary.core.reporter import Reporter
    from promptcanary.core.suite import CanarySuite
    from promptcanary.providers.litellm import LiteLLMProvider

    if not config.exists():
        err_console.print(
            f"[red]Config file not found:[/red] {config}\n"
            "Run [cyan]promptcanary init[/cyan] to create one."
        )
        raise typer.Exit(1)

    console.print(f"\n[dim]Loading suite from[/dim] [cyan]{config}[/cyan]…")

    try:
        suite = CanarySuite.from_yaml(config)
    except Exception as e:
        err_console.print(f"[red]Failed to load canary.yaml:[/red] {e}")
        raise typer.Exit(1) from e

    console.print(
        f"[dim]Suite:[/dim] [bold]{suite.name}[/bold]  "
        f"[dim]|[/dim]  {len(suite.prompts)} prompt(s)  "
        f"[dim]|[/dim]  {len(suite.probes)} probe(s)"
    )
    console.print(f"[dim]Provider:[/dim] [cyan]{provider}[/cyan]\n")

    llm_provider = LiteLLMProvider(
        provider, temperature=temperature, max_tokens=max_tokens, seed=seed
    )

    try:
        result = suite.run(
            llm_provider,
            temperature=temperature,
            max_tokens=max_tokens,
            seed=seed,
            show_progress=not no_progress,
        )
    except Exception as e:
        err_console.print(
            f"[red]Run failed:[/red] {e}\n\n"
            "Check your API key is set and the provider string is correct.\n"
            "Example: [cyan]export OPENAI_API_KEY=sk-...[/cyan]"
        )
        raise typer.Exit(1) from e

    # Print terminal report
    reporter = Reporter(result)
    reporter.print_terminal(console)

    # Save outputs
    if output_json:
        reporter.to_json(output_json)
        console.print(f"[dim]JSON saved:[/dim] {output_json}")

    if output_md:
        reporter.to_markdown(output_md)
        console.print(f"[dim]Markdown saved:[/dim] {output_md}")

    if output_html:
        reporter.to_html(output_html)
        console.print(f"[dim]HTML saved:[/dim] {output_html}")

    if save_baseline:
        from promptcanary.storage.file import FileBaselineStore

        store = FileBaselineStore(baseline_dir)
        snapshot = store.save(result)
        console.print(
            f"\n[green]✅ Baseline saved:[/green] "
            f"[cyan]{baseline_dir}/{snapshot.snapshot_id[:8]}…[/cyan]"
        )

    # Exit code for CI
    if fail_on_failure and result.failed_probes:
        raise typer.Exit(1)


# ─────────────────────────────────────────────────────────────────────────────
# compare
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def compare(
    config: Path = typer.Option(
        Path("canary.yaml"),
        "--config",
        "-c",
        help="Path to canary.yaml (used to run a fresh comparison).",
    ),
    provider: str | None = typer.Option(
        None,
        "--provider",
        "-p",
        help="Provider to run fresh comparison against (if --current not given).",
    ),
    baseline: Path | None = typer.Option(
        None,
        "--baseline",
        "-b",
        help="Path to baseline JSON file. If omitted, loads the most recent baseline.",
    ),
    current: Path | None = typer.Option(
        None,
        "--current",
        help="Path to current run JSON file. If omitted, runs a fresh query.",
    ),
    baseline_dir: Path = typer.Option(
        Path("baselines"),
        "--baseline-dir",
        help="Baseline storage directory.",
    ),
    output_md: Path | None = typer.Option(None, "--output-md"),
    output_html: Path | None = typer.Option(None, "--output-html"),
    fail_on_drift: bool = typer.Option(
        False,
        "--fail-on-drift",
        help="Exit with code 1 if drift is detected (for CI gating).",
    ),
    no_progress: bool = typer.Option(False, "--no-progress"),
) -> None:
    """Compare a current run against a saved baseline to detect drift.

    Either provide pre-existing JSON files via [cyan]--baseline[/cyan] and
    [cyan]--current[/cyan], or provide [cyan]--provider[/cyan] to run a
    fresh query and compare on the fly.

    [bold]Examples:[/bold]

    [dim]# Run fresh and compare to latest baseline[/dim]
    promptcanary compare --provider openai/gpt-5.4

    [dim]# Compare two saved files[/dim]
    promptcanary compare --baseline baselines/v1.json --current results.json --fail-on-drift
    """
    from promptcanary.core.comparator import compare as do_compare
    from promptcanary.core.models import CanaryRunResult
    from promptcanary.core.reporter import DriftReporter
    from promptcanary.storage.file import FileBaselineStore

    store = FileBaselineStore(baseline_dir)

    # Load baseline
    if baseline:
        console.print(f"[dim]Loading baseline from[/dim] [cyan]{baseline}[/cyan]…")
        baseline_snap = store.load_from_path(baseline)
    else:
        console.print(f"[dim]Loading latest baseline from[/dim] [cyan]{baseline_dir}/[/cyan]…")
        try:
            baseline_snap = store.load_latest(suite_name="*" if not config.exists() else "auto")
        except FileNotFoundError as e:
            err_console.print(
                f"[red]No baseline found:[/red] {e}\nRun with [cyan]--save-baseline[/cyan] first."
            )
            raise typer.Exit(1) from e

    # Load or generate current run
    if current:
        console.print(f"[dim]Loading current results from[/dim] [cyan]{current}[/cyan]…")
        data = json.loads(Path(current).read_text(encoding="utf-8"))
        current_result = CanaryRunResult.model_validate(data)
    elif provider:
        from promptcanary.core.suite import CanarySuite
        from promptcanary.providers.litellm import LiteLLMProvider

        if not config.exists():
            err_console.print(f"[red]Config not found:[/red] {config}")
            raise typer.Exit(1)

        suite = CanarySuite.from_yaml(config)
        llm = LiteLLMProvider(provider)
        console.print(f"[dim]Running fresh query against[/dim] [cyan]{provider}[/cyan]…")
        current_result = suite.run(llm, show_progress=not no_progress)
    else:
        err_console.print(
            "[red]Provide either --provider (for a fresh run) or --current (for a saved result).[/red]"
        )
        raise typer.Exit(1)

    # Compare
    try:
        drift = do_compare(baseline_snap, current_result)
    except ValueError as e:
        err_console.print(f"[red]Comparison error:[/red] {e}")
        raise typer.Exit(1) from e

    # Report
    reporter = DriftReporter(drift)
    reporter.print_terminal(console)

    if output_md:
        reporter.to_markdown(output_md)
        console.print(f"[dim]Markdown saved:[/dim] {output_md}")

    if output_html:
        reporter.to_html(output_html)
        console.print(f"[dim]HTML saved:[/dim] {output_html}")

    if fail_on_drift and drift.has_drift:
        raise typer.Exit(1)


# ─────────────────────────────────────────────────────────────────────────────
# baselines
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def baselines(
    baseline_dir: Path = typer.Option(Path("baselines"), "--dir", "-d"),
    suite: str | None = typer.Option(None, "--suite", "-s"),
) -> None:
    """List saved baseline snapshots."""
    from rich.table import Table

    from promptcanary.storage.file import FileBaselineStore

    store = FileBaselineStore(baseline_dir)
    items = store.list_baselines(suite_name=suite)

    if not items:
        console.print(f"[yellow]No baselines found in [cyan]{baseline_dir}[/cyan].[/yellow]")
        console.print("Run with [cyan]--save-baseline[/cyan] to create one.")
        return

    table = Table(title=f"Baselines — {baseline_dir}", show_lines=True)
    table.add_column("ID", style="cyan", no_wrap=True)
    table.add_column("Suite", style="bold")
    table.add_column("Model")
    table.add_column("Created At")
    table.add_column("Note")

    for item in items:
        snap_id = str(item["snapshot_id"])[:12]
        table.add_row(
            snap_id,
            str(item["suite_name"]),
            str(item["model_id"]),
            str(item["created_at"])[:19],
            str(item.get("note", "")),
        )

    console.print(table)


# ─────────────────────────────────────────────────────────────────────────────
# report  (offline: generate report from saved JSON)
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def report(
    input: Path = typer.Argument(..., help="Path to a saved JSON run result or drift report."),
    format: str = typer.Option(
        "terminal", "--format", "-f", help="Output format: terminal|markdown|html|json."
    ),
    output: Path | None = typer.Option(None, "--output", "-o", help="Save report to this path."),
    open_browser: bool = typer.Option(False, "--open", help="Open HTML report in browser."),
) -> None:
    """Generate a report from a saved JSON result file (offline mode)."""
    import webbrowser

    from promptcanary.core.models import CanaryRunResult, DriftReport
    from promptcanary.core.reporter import DriftReporter, Reporter

    if not input.exists():
        err_console.print(f"[red]File not found:[/red] {input}")
        raise typer.Exit(1)

    data = json.loads(input.read_text(encoding="utf-8"))

    # Detect whether it's a run result or drift report
    obj: CanaryRunResult | DriftReport
    reporter_obj: Reporter | DriftReporter
    if "comparisons" in data:
        obj = DriftReport.model_validate(data)
        reporter_obj = DriftReporter(obj)
    else:
        obj = CanaryRunResult.model_validate(data)
        reporter_obj = Reporter(obj)

    if format == "terminal":
        reporter_obj.print_terminal(console)
    elif format == "markdown":
        md = reporter_obj.to_markdown(output)
        if output:
            console.print(f"[dim]Saved:[/dim] {output}")
        else:
            console.print(md)
    elif format == "html":
        out_path = output or input.with_suffix(".html")
        reporter_obj.to_html(out_path)
        console.print(f"[dim]HTML saved:[/dim] {out_path}")
        if open_browser:
            webbrowser.open(str(out_path.absolute()))
    elif format == "json":
        js = reporter_obj.to_json(output)
        if not output:
            console.print(js)
    else:
        err_console.print(f"[red]Unknown format:[/red] {format}. Use: terminal|markdown|html|json")
        raise typer.Exit(1)


# ─────────────────────────────────────────────────────────────────────────────
# version
# ─────────────────────────────────────────────────────────────────────────────


@app.command()
def version() -> None:
    """Print PromptCanary version."""
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as pkg_version

    try:
        v = pkg_version("promptcanary")
    except PackageNotFoundError:
        v = "0.1.0-dev"
    console.print(f"PromptCanary [cyan]{v}[/cyan]")


if __name__ == "__main__":
    app()
